// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/wrapper/default_test_providers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:frontend/models/user/change_language_request.dart' as _i14;
import 'package:frontend/models/user/change_password_request.dart' as _i13;
import 'package:frontend/models/user/default_response.dart' as _i5;
import 'package:frontend/models/user/logged_user.dart' as _i4;
import 'package:frontend/models/user/login_request.dart' as _i10;
import 'package:frontend/models/user/provide_email_request.dart' as _i12;
import 'package:frontend/models/user/refreshed_tokens_response.dart' as _i6;
import 'package:frontend/models/user/register_request.dart' as _i11;
import 'package:frontend/models/user/user_response.dart' as _i3;
import 'package:frontend/repository/api_client.dart' as _i2;
import 'package:frontend/repository/user/user_repository.dart' as _i7;
import 'package:frontend/services/token_storage_service.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uuid/uuid_value.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_1 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoggedUser_2 extends _i1.SmartFake implements _i4.LoggedUser {
  _FakeLoggedUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDefaultResponse_3 extends _i1.SmartFake
    implements _i5.DefaultResponse {
  _FakeDefaultResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshedTokensResponse_4 extends _i1.SmartFake
    implements _i6.RefreshedTokensResponse {
  _FakeRefreshedTokensResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i8.Future<_i3.UserResponse> getUser(_i9.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i8.Future<_i3.UserResponse>.value(
              _FakeUserResponse_1(this, Invocation.method(#getUser, [userId])),
            ),
          )
          as _i8.Future<_i3.UserResponse>);

  @override
  _i8.Future<_i4.LoggedUser> login(_i10.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i4.LoggedUser>.value(
              _FakeLoggedUser_2(this, Invocation.method(#login, [request])),
            ),
          )
          as _i8.Future<_i4.LoggedUser>);

  @override
  _i8.Future<void> logout(_i9.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resendVerificationMail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationMail, [email]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> delete(_i9.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.DefaultResponse?> register(_i11.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i8.Future<_i5.DefaultResponse?>.value(),
          )
          as _i8.Future<_i5.DefaultResponse?>);

  @override
  _i8.Future<_i5.DefaultResponse> provideEmail(
    _i12.ProvideEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#provideEmail, [request]),
            returnValue: _i8.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#provideEmail, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.DefaultResponse>);

  @override
  _i8.Future<_i5.DefaultResponse> changePassword(
    _i13.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i8.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.DefaultResponse>);

  @override
  _i8.Future<_i5.DefaultResponse> changeLanguage(
    _i14.ChangeLanguageRequest? request,
    _i9.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [request, userId]),
            returnValue: _i8.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#changeLanguage, [request, userId]),
              ),
            ),
          )
          as _i8.Future<_i5.DefaultResponse>);

  @override
  _i8.Future<_i6.RefreshedTokensResponse> refreshTokens(
    _i9.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [userId]),
            returnValue: _i8.Future<_i6.RefreshedTokensResponse>.value(
              _FakeRefreshedTokensResponse_4(
                this,
                Invocation.method(#refreshTokens, [userId]),
              ),
            ),
          )
          as _i8.Future<_i6.RefreshedTokensResponse>);
}

/// A class which mocks [TokenStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageService extends _i1.Mock
    implements _i15.TokenStorageService {
  MockTokenStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> deleteAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
