// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i26;
import 'dart:ui' as _i24;

import 'package:dio/dio.dart' as _i22;
import 'package:dio/src/dio_mixin.dart' as _i23;
import 'package:dio_cache_interceptor/dio_cache_interceptor.dart' as _i25;
import 'package:flutter/foundation.dart' as _i48;
import 'package:flutter_bloc/flutter_bloc.dart' as _i35;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i21;
import 'package:frontend/blocs/user/register_bloc.dart' as _i33;
import 'package:frontend/events/user/register_events.dart' as _i34;
import 'package:frontend/foodini.dart' as _i49;
import 'package:frontend/models/diet_generation/composed_meal_item.dart'
    as _i17;
import 'package:frontend/models/diet_generation/custom_meal_update_request.dart'
    as _i43;
import 'package:frontend/models/diet_generation/daily_macros_summary_create.dart'
    as _i19;
import 'package:frontend/models/diet_generation/daily_meals_create.dart'
    as _i16;
import 'package:frontend/models/diet_generation/daily_summary.dart' as _i15;
import 'package:frontend/models/diet_generation/meal_create.dart' as _i20;
import 'package:frontend/models/diet_generation/meal_info_update_request.dart'
    as _i42;
import 'package:frontend/models/diet_generation/meal_recipe.dart' as _i14;
import 'package:frontend/models/diet_generation/meal_type.dart' as _i46;
import 'package:frontend/models/diet_generation/remove_meal_request.dart'
    as _i44;
import 'package:frontend/models/diet_generation/remove_meal_response.dart'
    as _i18;
import 'package:frontend/models/user/change_language_request.dart' as _i32;
import 'package:frontend/models/user/change_password_request.dart' as _i31;
import 'package:frontend/models/user/default_response.dart' as _i5;
import 'package:frontend/models/user/language.dart' as _i40;
import 'package:frontend/models/user/logged_user.dart' as _i4;
import 'package:frontend/models/user/login_request.dart' as _i28;
import 'package:frontend/models/user/provide_email_request.dart' as _i30;
import 'package:frontend/models/user/refreshed_tokens_response.dart' as _i6;
import 'package:frontend/models/user/register_request.dart' as _i29;
import 'package:frontend/models/user/user_response.dart' as _i3;
import 'package:frontend/models/user_details/diet_form.dart' as _i9;
import 'package:frontend/models/user_details/macros.dart' as _i38;
import 'package:frontend/models/user_details/predicted_calories.dart' as _i10;
import 'package:frontend/models/user_details/user_statistics.dart' as _i11;
import 'package:frontend/models/user_details/user_weight_history.dart' as _i12;
import 'package:frontend/repository/api_client.dart' as _i2;
import 'package:frontend/repository/diet_generation/diet_generation_repository.dart'
    as _i41;
import 'package:frontend/repository/diet_generation/diet_prediction_repository.dart'
    as _i39;
import 'package:frontend/repository/diet_generation/meals_repository.dart'
    as _i47;
import 'package:frontend/repository/user/user_repository.dart' as _i7;
import 'package:frontend/repository/user_details/user_details_repository.dart'
    as _i37;
import 'package:frontend/services/token_storage_service.dart' as _i36;
import 'package:frontend/states/register_states.dart' as _i8;
import 'package:frontend/utils/cache_manager.dart' as _i13;
import 'package:image_picker/image_picker.dart' as _i45;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uuid/uuid_value.dart' as _i27;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_1 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoggedUser_2 extends _i1.SmartFake implements _i4.LoggedUser {
  _FakeLoggedUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDefaultResponse_3 extends _i1.SmartFake
    implements _i5.DefaultResponse {
  _FakeDefaultResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshedTokensResponse_4 extends _i1.SmartFake
    implements _i6.RefreshedTokensResponse {
  _FakeRefreshedTokensResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserRepository_5 extends _i1.SmartFake
    implements _i7.UserRepository {
  _FakeUserRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterState_6 extends _i1.SmartFake implements _i8.RegisterState {
  _FakeRegisterState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDietForm_7 extends _i1.SmartFake implements _i9.DietForm {
  _FakeDietForm_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePredictedCalories_8 extends _i1.SmartFake
    implements _i10.PredictedCalories {
  _FakePredictedCalories_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserStatistics_9 extends _i1.SmartFake
    implements _i11.UserStatistics {
  _FakeUserStatistics_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserWeightHistory_10 extends _i1.SmartFake
    implements _i12.UserWeightHistory {
  _FakeUserWeightHistory_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCacheManager_11 extends _i1.SmartFake implements _i13.CacheManager {
  _FakeCacheManager_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealRecipe_12 extends _i1.SmartFake implements _i14.MealRecipe {
  _FakeMealRecipe_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailySummary_13 extends _i1.SmartFake implements _i15.DailySummary {
  _FakeDailySummary_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailyMealsCreate_14 extends _i1.SmartFake
    implements _i16.DailyMealsCreate {
  _FakeDailyMealsCreate_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComposedMealItem_15 extends _i1.SmartFake
    implements _i17.ComposedMealItem {
  _FakeComposedMealItem_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveMealResponse_16 extends _i1.SmartFake
    implements _i18.RemoveMealResponse {
  _FakeRemoveMealResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailyMacrosSummaryCreate_17 extends _i1.SmartFake
    implements _i19.DailyMacrosSummaryCreate {
  _FakeDailyMacrosSummaryCreate_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealCreate_18 extends _i1.SmartFake implements _i20.MealCreate {
  _FakeMealCreate_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_19 extends _i1.SmartFake implements _i21.IOSOptions {
  _FakeIOSOptions_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_20 extends _i1.SmartFake
    implements _i21.AndroidOptions {
  _FakeAndroidOptions_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_21 extends _i1.SmartFake implements _i21.LinuxOptions {
  _FakeLinuxOptions_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_22 extends _i1.SmartFake
    implements _i21.WindowsOptions {
  _FakeWindowsOptions_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_23 extends _i1.SmartFake implements _i21.WebOptions {
  _FakeWebOptions_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_24 extends _i1.SmartFake implements _i21.MacOsOptions {
  _FakeMacOsOptions_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_25 extends _i1.SmartFake implements _i22.Dio {
  _FakeDio_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_26<T> extends _i1.SmartFake implements _i22.Response<T> {
  _FakeResponse_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptorState_27<T> extends _i1.SmartFake
    implements _i23.InterceptorState<T> {
  _FakeInterceptorState_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_28 extends _i1.SmartFake implements _i24.Locale {
  _FakeLocale_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_29 extends _i1.SmartFake implements _i22.BaseOptions {
  _FakeBaseOptions_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_30 extends _i1.SmartFake implements _i22.Interceptors {
  _FakeInterceptors_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_31 extends _i1.SmartFake
    implements _i22.HttpClientAdapter {
  _FakeHttpClientAdapter_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_32 extends _i1.SmartFake implements _i22.Transformer {
  _FakeTransformer_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCacheStore_33 extends _i1.SmartFake implements _i25.CacheStore {
  _FakeCacheStore_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCacheOptions_34 extends _i1.SmartFake implements _i25.CacheOptions {
  _FakeCacheOptions_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i26.Future<_i3.UserResponse> getUser(_i27.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i26.Future<_i3.UserResponse>.value(
              _FakeUserResponse_1(this, Invocation.method(#getUser, [userId])),
            ),
          )
          as _i26.Future<_i3.UserResponse>);

  @override
  _i26.Future<_i4.LoggedUser> login(_i28.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i26.Future<_i4.LoggedUser>.value(
              _FakeLoggedUser_2(this, Invocation.method(#login, [request])),
            ),
          )
          as _i26.Future<_i4.LoggedUser>);

  @override
  _i26.Future<void> logout(_i27.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> resendVerificationMail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationMail, [email]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> delete(_i27.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [userId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i5.DefaultResponse?> register(_i29.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i26.Future<_i5.DefaultResponse?>.value(),
          )
          as _i26.Future<_i5.DefaultResponse?>);

  @override
  _i26.Future<_i5.DefaultResponse> provideEmail(
    _i30.ProvideEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#provideEmail, [request]),
            returnValue: _i26.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#provideEmail, [request]),
              ),
            ),
          )
          as _i26.Future<_i5.DefaultResponse>);

  @override
  _i26.Future<_i5.DefaultResponse> changePassword(
    _i31.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i26.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i26.Future<_i5.DefaultResponse>);

  @override
  _i26.Future<_i5.DefaultResponse> changeLanguage(
    _i32.ChangeLanguageRequest? request,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [request, userId]),
            returnValue: _i26.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#changeLanguage, [request, userId]),
              ),
            ),
          )
          as _i26.Future<_i5.DefaultResponse>);

  @override
  _i26.Future<_i6.RefreshedTokensResponse> refreshTokens(
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [userId]),
            returnValue: _i26.Future<_i6.RefreshedTokensResponse>.value(
              _FakeRefreshedTokensResponse_4(
                this,
                Invocation.method(#refreshTokens, [userId]),
              ),
            ),
          )
          as _i26.Future<_i6.RefreshedTokensResponse>);
}

/// A class which mocks [RegisterBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterBloc extends _i1.Mock implements _i33.RegisterBloc {
  MockRegisterBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.UserRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeUserRepository_5(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i7.UserRepository);

  @override
  _i8.RegisterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeRegisterState_6(this, Invocation.getter(#state)),
          )
          as _i8.RegisterState);

  @override
  _i26.Stream<_i8.RegisterState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i26.Stream<_i8.RegisterState>.empty(),
          )
          as _i26.Stream<_i8.RegisterState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i34.RegisterEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i34.RegisterEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i8.RegisterState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i34.RegisterEvent?>(
    _i35.EventHandler<E, _i8.RegisterState>? handler, {
    _i35.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i35.Transition<_i34.RegisterEvent?, _i8.RegisterState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i34.RegisterEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void onChange(_i35.Change<_i8.RegisterState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TokenStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageService extends _i1.Mock
    implements _i36.TokenStorageService {
  MockTokenStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i26.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<void> deleteAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [UserDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailsRepository extends _i1.Mock
    implements _i37.UserDetailsRepository {
  MockUserDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i26.Future<_i9.DietForm> getDietPreferences(_i27.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDietPreferences, [userId]),
            returnValue: _i26.Future<_i9.DietForm>.value(
              _FakeDietForm_7(
                this,
                Invocation.method(#getDietPreferences, [userId]),
              ),
            ),
          )
          as _i26.Future<_i9.DietForm>);

  @override
  _i26.Future<void> submitDietForm(
    _i9.DietForm? request,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitDietForm, [request, userId]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i10.PredictedCalories> submitMacrosChange(
    _i38.Macros? request,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitMacrosChange, [request, userId]),
            returnValue: _i26.Future<_i10.PredictedCalories>.value(
              _FakePredictedCalories_8(
                this,
                Invocation.method(#submitMacrosChange, [request, userId]),
              ),
            ),
          )
          as _i26.Future<_i10.PredictedCalories>);

  @override
  _i26.Future<_i10.PredictedCalories> addCaloriesPrediction(
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCaloriesPrediction, [userId]),
            returnValue: _i26.Future<_i10.PredictedCalories>.value(
              _FakePredictedCalories_8(
                this,
                Invocation.method(#addCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i26.Future<_i10.PredictedCalories>);

  @override
  _i26.Future<_i10.PredictedCalories> getCaloriesPrediction(
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCaloriesPrediction, [userId]),
            returnValue: _i26.Future<_i10.PredictedCalories>.value(
              _FakePredictedCalories_8(
                this,
                Invocation.method(#getCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i26.Future<_i10.PredictedCalories>);

  @override
  _i26.Future<_i11.UserStatistics> getUserStatistics(_i27.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatistics, [userId]),
            returnValue: _i26.Future<_i11.UserStatistics>.value(
              _FakeUserStatistics_9(
                this,
                Invocation.method(#getUserStatistics, [userId]),
              ),
            ),
          )
          as _i26.Future<_i11.UserStatistics>);

  @override
  _i26.Future<_i12.UserWeightHistory?> getUserWeightForDay(
    DateTime? day,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserWeightForDay, [day, userId]),
            returnValue: _i26.Future<_i12.UserWeightHistory?>.value(),
          )
          as _i26.Future<_i12.UserWeightHistory?>);

  @override
  _i26.Future<List<_i12.UserWeightHistory>> getUserWeightHistory({
    required DateTime? start,
    required DateTime? end,
    required _i27.UuidValue? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserWeightHistory, [], {
              #start: start,
              #end: end,
              #userId: userId,
            }),
            returnValue: _i26.Future<List<_i12.UserWeightHistory>>.value(
              <_i12.UserWeightHistory>[],
            ),
          )
          as _i26.Future<List<_i12.UserWeightHistory>>);

  @override
  _i26.Future<_i12.UserWeightHistory> addOrUpdateUserWeight(
    _i12.UserWeightHistory? request,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addOrUpdateUserWeight, [request, userId]),
            returnValue: _i26.Future<_i12.UserWeightHistory>.value(
              _FakeUserWeightHistory_10(
                this,
                Invocation.method(#addOrUpdateUserWeight, [request, userId]),
              ),
            ),
          )
          as _i26.Future<_i12.UserWeightHistory>);
}

/// A class which mocks [DietPredictionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDietPredictionRepository extends _i1.Mock
    implements _i39.DietPredictionRepository {
  MockDietPredictionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i13.CacheManager get cacheManager =>
      (super.noSuchMethod(
            Invocation.getter(#cacheManager),
            returnValue: _FakeCacheManager_11(
              this,
              Invocation.getter(#cacheManager),
            ),
          )
          as _i13.CacheManager);

  @override
  _i26.Future<_i14.MealRecipe> getMealRecipe(
    _i27.UuidValue? userId,
    _i27.UuidValue? mealId,
    _i40.Language? language,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealRecipe, [userId, mealId, language]),
            returnValue: _i26.Future<_i14.MealRecipe>.value(
              _FakeMealRecipe_12(
                this,
                Invocation.method(#getMealRecipe, [userId, mealId, language]),
              ),
            ),
          )
          as _i26.Future<_i14.MealRecipe>);
}

/// A class which mocks [DietGenerationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDietGenerationRepository extends _i1.Mock
    implements _i41.DietGenerationRepository {
  MockDietGenerationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i13.CacheManager get cacheManager =>
      (super.noSuchMethod(
            Invocation.getter(#cacheManager),
            returnValue: _FakeCacheManager_11(
              this,
              Invocation.getter(#cacheManager),
            ),
          )
          as _i13.CacheManager);

  @override
  _i26.Future<_i15.DailySummary> getDailySummary(
    DateTime? day,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummary, [day, userId]),
            returnValue: _i26.Future<_i15.DailySummary>.value(
              _FakeDailySummary_13(
                this,
                Invocation.method(#getDailySummary, [day, userId]),
              ),
            ),
          )
          as _i26.Future<_i15.DailySummary>);

  @override
  _i26.Future<_i16.DailyMealsCreate> getDailySummaryMeals(
    DateTime? day,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummaryMeals, [day, userId]),
            returnValue: _i26.Future<_i16.DailyMealsCreate>.value(
              _FakeDailyMealsCreate_14(
                this,
                Invocation.method(#getDailySummaryMeals, [day, userId]),
              ),
            ),
          )
          as _i26.Future<_i16.DailyMealsCreate>);

  @override
  _i26.Future<void> updateDailySummaryMeals(
    _i42.MealInfoUpdateRequest? mealInfoUpdateRequest,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDailySummaryMeals, [
              mealInfoUpdateRequest,
              userId,
            ]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<_i17.ComposedMealItem> addCustomMeal(
    _i43.CustomMealUpdateRequest? customMealUpdateRequest,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCustomMeal, [
              customMealUpdateRequest,
              userId,
            ]),
            returnValue: _i26.Future<_i17.ComposedMealItem>.value(
              _FakeComposedMealItem_15(
                this,
                Invocation.method(#addCustomMeal, [
                  customMealUpdateRequest,
                  userId,
                ]),
              ),
            ),
          )
          as _i26.Future<_i17.ComposedMealItem>);

  @override
  _i26.Future<_i17.ComposedMealItem> updateCustomMeal(
    _i43.CustomMealUpdateRequest? customMealUpdateRequest,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomMeal, [
              customMealUpdateRequest,
              userId,
            ]),
            returnValue: _i26.Future<_i17.ComposedMealItem>.value(
              _FakeComposedMealItem_15(
                this,
                Invocation.method(#updateCustomMeal, [
                  customMealUpdateRequest,
                  userId,
                ]),
              ),
            ),
          )
          as _i26.Future<_i17.ComposedMealItem>);

  @override
  _i26.Future<_i18.RemoveMealResponse> removeMealFromSummary(
    _i44.RemoveMealRequest? removeMealRequest,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeMealFromSummary, [
              removeMealRequest,
              userId,
            ]),
            returnValue: _i26.Future<_i18.RemoveMealResponse>.value(
              _FakeRemoveMealResponse_16(
                this,
                Invocation.method(#removeMealFromSummary, [
                  removeMealRequest,
                  userId,
                ]),
              ),
            ),
          )
          as _i26.Future<_i18.RemoveMealResponse>);

  @override
  _i26.Future<_i17.ComposedMealItem> addScannedProduct({
    String? barcode,
    _i45.XFile? uploadedFile,
    required _i46.MealType? mealType,
    required DateTime? day,
    required _i27.UuidValue? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addScannedProduct, [], {
              #barcode: barcode,
              #uploadedFile: uploadedFile,
              #mealType: mealType,
              #day: day,
              #userId: userId,
            }),
            returnValue: _i26.Future<_i17.ComposedMealItem>.value(
              _FakeComposedMealItem_15(
                this,
                Invocation.method(#addScannedProduct, [], {
                  #barcode: barcode,
                  #uploadedFile: uploadedFile,
                  #mealType: mealType,
                  #day: day,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i26.Future<_i17.ComposedMealItem>);

  @override
  _i26.Future<_i19.DailyMacrosSummaryCreate> getDailySummaryMacros(
    DateTime? day,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummaryMacros, [day, userId]),
            returnValue: _i26.Future<_i19.DailyMacrosSummaryCreate>.value(
              _FakeDailyMacrosSummaryCreate_17(
                this,
                Invocation.method(#getDailySummaryMacros, [day, userId]),
              ),
            ),
          )
          as _i26.Future<_i19.DailyMacrosSummaryCreate>);

  @override
  _i26.Future<void> generateMealPlan(_i27.UuidValue? userId, DateTime? day) =>
      (super.noSuchMethod(
            Invocation.method(#generateMealPlan, [userId, day]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [MealsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealsRepository extends _i1.Mock implements _i47.MealsRepository {
  MockMealsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i13.CacheManager get cacheManager =>
      (super.noSuchMethod(
            Invocation.getter(#cacheManager),
            returnValue: _FakeCacheManager_11(
              this,
              Invocation.getter(#cacheManager),
            ),
          )
          as _i13.CacheManager);

  @override
  _i26.Future<_i20.MealCreate> getMealDetails(
    _i27.UuidValue? mealId,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealDetails, [mealId, userId]),
            returnValue: _i26.Future<_i20.MealCreate>.value(
              _FakeMealCreate_18(
                this,
                Invocation.method(#getMealDetails, [mealId, userId]),
              ),
            ),
          )
          as _i26.Future<_i20.MealCreate>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i21.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i21.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_19(this, Invocation.getter(#iOptions)),
          )
          as _i21.IOSOptions);

  @override
  _i21.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_20(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i21.AndroidOptions);

  @override
  _i21.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_21(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i21.LinuxOptions);

  @override
  _i21.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_22(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i21.WindowsOptions);

  @override
  _i21.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_23(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i21.WebOptions);

  @override
  _i21.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_24(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i21.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i48.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i48.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> write({
    required String? key,
    required String? value,
    _i21.IOSOptions? iOptions,
    _i21.AndroidOptions? aOptions,
    _i21.LinuxOptions? lOptions,
    _i21.WebOptions? webOptions,
    _i21.MacOsOptions? mOptions,
    _i21.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String?> read({
    required String? key,
    _i21.IOSOptions? iOptions,
    _i21.AndroidOptions? aOptions,
    _i21.LinuxOptions? lOptions,
    _i21.WebOptions? webOptions,
    _i21.MacOsOptions? mOptions,
    _i21.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<bool> containsKey({
    required String? key,
    _i21.IOSOptions? iOptions,
    _i21.AndroidOptions? aOptions,
    _i21.LinuxOptions? lOptions,
    _i21.WebOptions? webOptions,
    _i21.MacOsOptions? mOptions,
    _i21.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i26.Future<bool>.value(false),
          )
          as _i26.Future<bool>);

  @override
  _i26.Future<void> delete({
    required String? key,
    _i21.IOSOptions? iOptions,
    _i21.AndroidOptions? aOptions,
    _i21.LinuxOptions? lOptions,
    _i21.WebOptions? webOptions,
    _i21.MacOsOptions? mOptions,
    _i21.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<Map<String, String>> readAll({
    _i21.IOSOptions? iOptions,
    _i21.AndroidOptions? aOptions,
    _i21.LinuxOptions? lOptions,
    _i21.WebOptions? webOptions,
    _i21.MacOsOptions? mOptions,
    _i21.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i26.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i26.Future<Map<String, String>>);

  @override
  _i26.Future<void> deleteAll({
    _i21.IOSOptions? iOptions,
    _i21.AndroidOptions? aOptions,
    _i21.LinuxOptions? lOptions,
    _i21.WebOptions? webOptions,
    _i21.MacOsOptions? mOptions,
    _i21.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i26.Future<bool?>.value(),
          )
          as _i26.Future<bool?>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i22.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_25(this, Invocation.getter(#dio)),
          )
          as _i22.Dio);

  @override
  _i26.Future<_i22.Response<dynamic>> getUser(_i27.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getUser, [userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> register(_i29.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> login(_i28.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> provideEmail(
    _i30.ProvideEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#provideEmail, [request]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#provideEmail, [request]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> changePassword(
    _i31.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> changeLanguage(
    _i32.ChangeLanguageRequest? request,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [request, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#changeLanguage, [request, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> refreshTokens(_i27.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#refreshTokens, [userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> logout(_i27.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#logout, [userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> resendVerificationMail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationMail, [email]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#resendVerificationMail, [email]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> delete(_i27.UuidValue? userId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#delete, [userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> refreshRequest(
    _i22.RequestOptions? requestOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshRequest, [requestOptions]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#refreshRequest, [requestOptions]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getUserStatistics(
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatistics, [userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getUserStatistics, [userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getUserWeightForDay(
    DateTime? day,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserWeightForDay, [day, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getUserWeightForDay, [day, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getWeightHistory({
    required DateTime? start,
    required DateTime? end,
    required _i27.UuidValue? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWeightHistory, [], {
              #start: start,
              #end: end,
              #userId: userId,
            }),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getWeightHistory, [], {
                  #start: start,
                  #end: end,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> addUserWeight(
    Map<String, dynamic>? body,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addUserWeight, [body, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#addUserWeight, [body, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getDietPreferences(
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDietPreferences, [userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getDietPreferences, [userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> submitDietForm(
    _i9.DietForm? request,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitDietForm, [request, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#submitDietForm, [request, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> submitMacrosChange(
    _i38.Macros? request,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitMacrosChange, [request, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#submitMacrosChange, [request, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> addCaloriesPrediction(
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCaloriesPrediction, [userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#addCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getCaloriesPrediction(
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCaloriesPrediction, [userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getMealRecipe(
    _i27.UuidValue? mealId,
    _i40.Language? language,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealRecipe, [mealId, language, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getMealRecipe, [mealId, language, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> generateMealPlan(
    _i27.UuidValue? userId,
    DateTime? day,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateMealPlan, [userId, day]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#generateMealPlan, [userId, day]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getDailySummary(
    DateTime? day,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummary, [day, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getDailySummary, [day, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getDailySummaryMeals(
    DateTime? day,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummaryMeals, [day, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getDailySummaryMeals, [day, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> updateDailySummaryMeals(
    _i42.MealInfoUpdateRequest? mealInfoUpdateRequest,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDailySummaryMeals, [
              mealInfoUpdateRequest,
              userId,
            ]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#updateDailySummaryMeals, [
                  mealInfoUpdateRequest,
                  userId,
                ]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getDailySummaryMacros(
    DateTime? day,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummaryMacros, [day, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getDailySummaryMacros, [day, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getMealDetails(
    _i27.UuidValue? mealId,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealDetails, [mealId, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getMealDetails, [mealId, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> getMealIconInfo(
    _i46.MealType? mealType,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealIconInfo, [mealType, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#getMealIconInfo, [mealType, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> addMeal(
    _i43.CustomMealUpdateRequest? customMealUpdateRequest,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMeal, [customMealUpdateRequest, userId]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#addMeal, [customMealUpdateRequest, userId]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> updateDailyMeal(
    _i43.CustomMealUpdateRequest? customMealUpdateRequest,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDailyMeal, [
              customMealUpdateRequest,
              userId,
            ]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#updateDailyMeal, [
                  customMealUpdateRequest,
                  userId,
                ]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> removeMealFromSummary(
    _i44.RemoveMealRequest? removeMealRequest,
    _i27.UuidValue? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeMealFromSummary, [
              removeMealRequest,
              userId,
            ]),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#removeMealFromSummary, [
                  removeMealRequest,
                  userId,
                ]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> addScannedProduct({
    String? barcode,
    _i45.XFile? uploadedFile,
    required _i46.MealType? mealType,
    required DateTime? day,
    required _i27.UuidValue? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addScannedProduct, [], {
              #barcode: barcode,
              #uploadedFile: uploadedFile,
              #mealType: mealType,
              #day: day,
              #userId: userId,
            }),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(#addScannedProduct, [], {
                  #barcode: barcode,
                  #uploadedFile: uploadedFile,
                  #mealType: mealType,
                  #day: day,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);
}

/// A class which mocks [ErrorInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorInterceptorHandler extends _i1.Mock
    implements _i22.ErrorInterceptorHandler {
  MockErrorInterceptorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i26.Future<_i23.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i26.Future<_i23.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_27<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
          )
          as _i26.Future<_i23.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(Invocation.getter(#isCompleted), returnValue: false)
          as bool);

  @override
  void next(_i22.DioException? error) => super.noSuchMethod(
    Invocation.method(#next, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(_i22.Response<dynamic>? response) => super.noSuchMethod(
    Invocation.method(#resolve, [response]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(_i22.DioException? error) => super.noSuchMethod(
    Invocation.method(#reject, [error]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LanguageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageCubit extends _i1.Mock implements _i49.LanguageCubit {
  MockLanguageCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Locale get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeLocale_28(this, Invocation.getter(#state)),
          )
          as _i24.Locale);

  @override
  _i26.Stream<_i24.Locale> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i26.Stream<_i24.Locale>.empty(),
          )
          as _i26.Stream<_i24.Locale>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i26.Future<void> change(_i40.Language? language) =>
      (super.noSuchMethod(
            Invocation.method(#change, [language]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void emit(_i24.Locale? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i35.Change<_i24.Locale>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i22.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i22.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_29(this, Invocation.getter(#options)),
          )
          as _i22.BaseOptions);

  @override
  _i22.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_30(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i22.Interceptors);

  @override
  _i22.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_31(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i22.HttpClientAdapter);

  @override
  _i22.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_32(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i22.Transformer);

  @override
  set options(_i22.BaseOptions? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i22.HttpClientAdapter? value) => super.noSuchMethod(
    Invocation.setter(#httpClientAdapter, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformer(_i22.Transformer? value) => super.noSuchMethod(
    Invocation.setter(#transformer, value),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<_i22.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
    _i22.ProgressCallback? onSendProgress,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
    _i22.ProgressCallback? onSendProgress,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
    _i22.ProgressCallback? onSendProgress,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
    _i22.ProgressCallback? onSendProgress,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
    _i22.ProgressCallback? onSendProgress,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
    _i22.ProgressCallback? onSendProgress,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i22.Options? options,
    _i22.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i22.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i22.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i22.FileAccessMode? fileAccessMode = _i22.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i22.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i22.ProgressCallback? onReceiveProgress,
    _i22.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i22.FileAccessMode? fileAccessMode = _i22.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i22.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i26.Future<_i22.Response<dynamic>>.value(
              _FakeResponse_26<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<dynamic>>);

  @override
  _i26.Future<_i22.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i22.CancelToken? cancelToken,
    _i22.Options? options,
    _i22.ProgressCallback? onSendProgress,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i22.CancelToken? cancelToken,
    _i22.Options? options,
    _i22.ProgressCallback? onSendProgress,
    _i22.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i26.Future<_i22.Response<T>> fetch<T>(_i22.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i26.Future<_i22.Response<T>>.value(
              _FakeResponse_26<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i26.Future<_i22.Response<T>>);

  @override
  _i22.Dio clone({
    _i22.BaseOptions? options,
    _i22.Interceptors? interceptors,
    _i22.HttpClientAdapter? httpClientAdapter,
    _i22.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_25(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i22.Dio);
}

/// A class which mocks [CacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheManager extends _i1.Mock implements _i13.CacheManager {
  MockCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.CacheStore get cacheStore =>
      (super.noSuchMethod(
            Invocation.getter(#cacheStore),
            returnValue: _FakeCacheStore_33(
              this,
              Invocation.getter(#cacheStore),
            ),
          )
          as _i25.CacheStore);

  @override
  _i25.CacheOptions get cacheOptions =>
      (super.noSuchMethod(
            Invocation.getter(#cacheOptions),
            returnValue: _FakeCacheOptions_34(
              this,
              Invocation.getter(#cacheOptions),
            ),
          )
          as _i25.CacheOptions);

  @override
  set cacheStore(_i25.CacheStore? value) => super.noSuchMethod(
    Invocation.setter(#cacheStore, value),
    returnValueForMissingStub: null,
  );

  @override
  set cacheOptions(_i25.CacheOptions? value) => super.noSuchMethod(
    Invocation.setter(#cacheOptions, value),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> clearCacheFor(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#clearCacheFor, [url]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}
