// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;
import 'dart:ui' as _i14;

import 'package:dio/dio.dart' as _i12;
import 'package:dio/src/dio_mixin.dart' as _i13;
import 'package:flutter/foundation.dart' as _i27;
import 'package:flutter_bloc/flutter_bloc.dart' as _i23;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i11;
import 'package:frontend/blocs/user/register_bloc.dart' as _i21;
import 'package:frontend/events/user/register_events.dart' as _i22;
import 'package:frontend/foodini.dart' as _i28;
import 'package:frontend/models/user/change_language_request.dart' as _i20;
import 'package:frontend/models/user/change_password_request.dart' as _i19;
import 'package:frontend/models/user/default_response.dart' as _i5;
import 'package:frontend/models/user/language.dart' as _i29;
import 'package:frontend/models/user/logged_user.dart' as _i4;
import 'package:frontend/models/user/login_request.dart' as _i16;
import 'package:frontend/models/user/provide_email_request.dart' as _i18;
import 'package:frontend/models/user/refreshed_tokens_response.dart' as _i6;
import 'package:frontend/models/user/register_request.dart' as _i17;
import 'package:frontend/models/user/user_response.dart' as _i3;
import 'package:frontend/models/user_details/diet_form.dart' as _i9;
import 'package:frontend/models/user_details/predicted_calories.dart' as _i10;
import 'package:frontend/models/user_details/predicted_macros.dart' as _i26;
import 'package:frontend/repository/user/user_repository.dart' as _i7;
import 'package:frontend/repository/user_details/user_details_repository.dart'
    as _i25;
import 'package:frontend/services/api_client.dart' as _i2;
import 'package:frontend/services/token_storage_service.dart' as _i24;
import 'package:frontend/states/register_states.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_1 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoggedUser_2 extends _i1.SmartFake implements _i4.LoggedUser {
  _FakeLoggedUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDefaultResponse_3 extends _i1.SmartFake
    implements _i5.DefaultResponse {
  _FakeDefaultResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshedTokensResponse_4 extends _i1.SmartFake
    implements _i6.RefreshedTokensResponse {
  _FakeRefreshedTokensResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserRepository_5 extends _i1.SmartFake
    implements _i7.UserRepository {
  _FakeUserRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterState_6 extends _i1.SmartFake implements _i8.RegisterState {
  _FakeRegisterState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDietForm_7 extends _i1.SmartFake implements _i9.DietForm {
  _FakeDietForm_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePredictedCalories_8 extends _i1.SmartFake
    implements _i10.PredictedCalories {
  _FakePredictedCalories_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_9 extends _i1.SmartFake implements _i11.IOSOptions {
  _FakeIOSOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_10 extends _i1.SmartFake
    implements _i11.AndroidOptions {
  _FakeAndroidOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_11 extends _i1.SmartFake implements _i11.LinuxOptions {
  _FakeLinuxOptions_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_12 extends _i1.SmartFake
    implements _i11.WindowsOptions {
  _FakeWindowsOptions_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_13 extends _i1.SmartFake implements _i11.WebOptions {
  _FakeWebOptions_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_14 extends _i1.SmartFake implements _i11.MacOsOptions {
  _FakeMacOsOptions_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_15<T> extends _i1.SmartFake implements _i12.Response<T> {
  _FakeResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptorState_16<T> extends _i1.SmartFake
    implements _i13.InterceptorState<T> {
  _FakeInterceptorState_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_17 extends _i1.SmartFake implements _i14.Locale {
  _FakeLocale_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_18 extends _i1.SmartFake implements _i12.BaseOptions {
  _FakeBaseOptions_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_19 extends _i1.SmartFake
    implements _i12.HttpClientAdapter {
  _FakeHttpClientAdapter_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_20 extends _i1.SmartFake implements _i12.Transformer {
  _FakeTransformer_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_21 extends _i1.SmartFake implements _i12.Interceptors {
  _FakeInterceptors_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_22 extends _i1.SmartFake implements _i12.Dio {
  _FakeDio_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i15.Future<_i3.UserResponse> getUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i15.Future<_i3.UserResponse>.value(
              _FakeUserResponse_1(this, Invocation.method(#getUser, [userId])),
            ),
          )
          as _i15.Future<_i3.UserResponse>);

  @override
  _i15.Future<_i4.LoggedUser> login(_i16.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i15.Future<_i4.LoggedUser>.value(
              _FakeLoggedUser_2(this, Invocation.method(#login, [request])),
            ),
          )
          as _i15.Future<_i4.LoggedUser>);

  @override
  _i15.Future<void> logout(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> resendVerificationMail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationMail, [email]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> delete(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [userId]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i5.DefaultResponse?> register(_i17.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i15.Future<_i5.DefaultResponse?>.value(),
          )
          as _i15.Future<_i5.DefaultResponse?>);

  @override
  _i15.Future<_i5.DefaultResponse> provideEmail(
    _i18.ProvideEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#provideEmail, [request]),
            returnValue: _i15.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#provideEmail, [request]),
              ),
            ),
          )
          as _i15.Future<_i5.DefaultResponse>);

  @override
  _i15.Future<_i5.DefaultResponse> changePassword(
    _i19.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i15.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i15.Future<_i5.DefaultResponse>);

  @override
  _i15.Future<_i5.DefaultResponse> changeLanguage(
    _i20.ChangeLanguageRequest? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [request, userId]),
            returnValue: _i15.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#changeLanguage, [request, userId]),
              ),
            ),
          )
          as _i15.Future<_i5.DefaultResponse>);

  @override
  _i15.Future<_i6.RefreshedTokensResponse> refreshTokens(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [userId]),
            returnValue: _i15.Future<_i6.RefreshedTokensResponse>.value(
              _FakeRefreshedTokensResponse_4(
                this,
                Invocation.method(#refreshTokens, [userId]),
              ),
            ),
          )
          as _i15.Future<_i6.RefreshedTokensResponse>);
}

/// A class which mocks [RegisterBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterBloc extends _i1.Mock implements _i21.RegisterBloc {
  MockRegisterBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.UserRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeUserRepository_5(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i7.UserRepository);

  @override
  _i8.RegisterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeRegisterState_6(this, Invocation.getter(#state)),
          )
          as _i8.RegisterState);

  @override
  _i15.Stream<_i8.RegisterState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i15.Stream<_i8.RegisterState>.empty(),
          )
          as _i15.Stream<_i8.RegisterState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i22.RegisterEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i22.RegisterEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i8.RegisterState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i22.RegisterEvent?>(
    _i23.EventHandler<E, _i8.RegisterState>? handler, {
    _i23.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i23.Transition<_i22.RegisterEvent?, _i8.RegisterState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void onChange(_i23.Change<_i8.RegisterState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TokenStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageRepository extends _i1.Mock
    implements _i24.TokenStorageRepository {
  MockTokenStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i15.Future<String?>.value(),
          )
          as _i15.Future<String?>);

  @override
  _i15.Future<void> deleteAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i15.Future<String?>.value(),
          )
          as _i15.Future<String?>);

  @override
  _i15.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [UserDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailsRepository extends _i1.Mock
    implements _i25.UserDetailsRepository {
  MockUserDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i15.Future<_i9.DietForm> getDietPreferences(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDietPreferences, [userId]),
            returnValue: _i15.Future<_i9.DietForm>.value(
              _FakeDietForm_7(
                this,
                Invocation.method(#getDietPreferences, [userId]),
              ),
            ),
          )
          as _i15.Future<_i9.DietForm>);

  @override
  _i15.Future<void> submitDietForm(_i9.DietForm? request, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#submitDietForm, [request, userId]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> submitMacrosChange(
    _i26.PredictedMacros? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitMacrosChange, [request, userId]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i10.PredictedCalories> addCaloriesPrediction(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addCaloriesPrediction, [userId]),
            returnValue: _i15.Future<_i10.PredictedCalories>.value(
              _FakePredictedCalories_8(
                this,
                Invocation.method(#addCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i15.Future<_i10.PredictedCalories>);

  @override
  _i15.Future<_i10.PredictedCalories> getCaloriesPrediction(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCaloriesPrediction, [userId]),
            returnValue: _i15.Future<_i10.PredictedCalories>.value(
              _FakePredictedCalories_8(
                this,
                Invocation.method(#getCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i15.Future<_i10.PredictedCalories>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i11.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_9(this, Invocation.getter(#iOptions)),
          )
          as _i11.IOSOptions);

  @override
  _i11.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_10(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i11.AndroidOptions);

  @override
  _i11.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_11(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i11.LinuxOptions);

  @override
  _i11.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_12(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i11.WindowsOptions);

  @override
  _i11.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_13(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i11.WebOptions);

  @override
  _i11.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_14(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i11.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i27.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i27.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> write({
    required String? key,
    required String? value,
    _i11.IOSOptions? iOptions,
    _i11.AndroidOptions? aOptions,
    _i11.LinuxOptions? lOptions,
    _i11.WebOptions? webOptions,
    _i11.MacOsOptions? mOptions,
    _i11.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String?> read({
    required String? key,
    _i11.IOSOptions? iOptions,
    _i11.AndroidOptions? aOptions,
    _i11.LinuxOptions? lOptions,
    _i11.WebOptions? webOptions,
    _i11.MacOsOptions? mOptions,
    _i11.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i15.Future<String?>.value(),
          )
          as _i15.Future<String?>);

  @override
  _i15.Future<bool> containsKey({
    required String? key,
    _i11.IOSOptions? iOptions,
    _i11.AndroidOptions? aOptions,
    _i11.LinuxOptions? lOptions,
    _i11.WebOptions? webOptions,
    _i11.MacOsOptions? mOptions,
    _i11.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> delete({
    required String? key,
    _i11.IOSOptions? iOptions,
    _i11.AndroidOptions? aOptions,
    _i11.LinuxOptions? lOptions,
    _i11.WebOptions? webOptions,
    _i11.MacOsOptions? mOptions,
    _i11.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<Map<String, String>> readAll({
    _i11.IOSOptions? iOptions,
    _i11.AndroidOptions? aOptions,
    _i11.LinuxOptions? lOptions,
    _i11.WebOptions? webOptions,
    _i11.MacOsOptions? mOptions,
    _i11.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i15.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i15.Future<Map<String, String>>);

  @override
  _i15.Future<void> deleteAll({
    _i11.IOSOptions? iOptions,
    _i11.AndroidOptions? aOptions,
    _i11.LinuxOptions? lOptions,
    _i11.WebOptions? webOptions,
    _i11.MacOsOptions? mOptions,
    _i11.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i15.Future<bool?>.value(),
          )
          as _i15.Future<bool?>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i12.Response<dynamic>> getUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#getUser, [userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> register(_i17.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> login(_i16.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> provideEmail(
    _i18.ProvideEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#provideEmail, [request]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#provideEmail, [request]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> changePassword(
    _i19.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> changeLanguage(
    _i20.ChangeLanguageRequest? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [request, userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#changeLanguage, [request, userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> refreshTokens(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#refreshTokens, [userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> logout(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#logout, [userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> resendVerificationMail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationMail, [email]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#resendVerificationMail, [email]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> delete(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#delete, [userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> refreshRequest(
    _i12.RequestOptions? requestOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshRequest, [requestOptions]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#refreshRequest, [requestOptions]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> getDietPreferences(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDietPreferences, [userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#getDietPreferences, [userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> submitDietForm(
    _i9.DietForm? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitDietForm, [request, userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#submitDietForm, [request, userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> submitMacrosChange(
    _i26.PredictedMacros? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitMacrosChange, [request, userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#submitMacrosChange, [request, userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> addCaloriesPrediction(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addCaloriesPrediction, [userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#addCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> getCaloriesPrediction(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCaloriesPrediction, [userId]),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(#getCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);
}

/// A class which mocks [ErrorInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorInterceptorHandler extends _i1.Mock
    implements _i12.ErrorInterceptorHandler {
  MockErrorInterceptorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i13.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i15.Future<_i13.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_16<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
          )
          as _i15.Future<_i13.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(Invocation.getter(#isCompleted), returnValue: false)
          as bool);

  @override
  void next(_i12.DioException? error) => super.noSuchMethod(
    Invocation.method(#next, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(_i12.Response<dynamic>? response) => super.noSuchMethod(
    Invocation.method(#resolve, [response]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(_i12.DioException? error) => super.noSuchMethod(
    Invocation.method(#reject, [error]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LanguageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageCubit extends _i1.Mock implements _i28.LanguageCubit {
  MockLanguageCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Locale get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeLocale_17(this, Invocation.getter(#state)),
          )
          as _i14.Locale);

  @override
  _i15.Stream<_i14.Locale> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i15.Stream<_i14.Locale>.empty(),
          )
          as _i15.Stream<_i14.Locale>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i15.Future<void> change(_i29.Language? language) =>
      (super.noSuchMethod(
            Invocation.method(#change, [language]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void emit(_i14.Locale? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i23.Change<_i14.Locale>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i12.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_18(this, Invocation.getter(#options)),
          )
          as _i12.BaseOptions);

  @override
  _i12.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_19(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i12.HttpClientAdapter);

  @override
  _i12.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_20(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i12.Transformer);

  @override
  _i12.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_21(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i12.Interceptors);

  @override
  set options(_i12.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i12.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i12.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<_i12.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
    _i12.ProgressCallback? onSendProgress,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
    _i12.ProgressCallback? onSendProgress,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
    _i12.ProgressCallback? onSendProgress,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
    _i12.ProgressCallback? onSendProgress,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
    _i12.ProgressCallback? onSendProgress,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
    _i12.ProgressCallback? onSendProgress,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i12.Options? options,
    _i12.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i12.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i12.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i12.FileAccessMode? fileAccessMode = _i12.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i12.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i12.ProgressCallback? onReceiveProgress,
    _i12.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i12.FileAccessMode? fileAccessMode = _i12.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i12.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i15.Future<_i12.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<dynamic>>);

  @override
  _i15.Future<_i12.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i12.CancelToken? cancelToken,
    _i12.Options? options,
    _i12.ProgressCallback? onSendProgress,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i12.CancelToken? cancelToken,
    _i12.Options? options,
    _i12.ProgressCallback? onSendProgress,
    _i12.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i15.Future<_i12.Response<T>> fetch<T>(_i12.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i15.Future<_i12.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i15.Future<_i12.Response<T>>);

  @override
  _i12.Dio clone({
    _i12.BaseOptions? options,
    _i12.Interceptors? interceptors,
    _i12.HttpClientAdapter? httpClientAdapter,
    _i12.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_22(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i12.Dio);
}
