// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;
import 'dart:ui' as _i17;

import 'package:dio/dio.dart' as _i15;
import 'package:dio/src/dio_mixin.dart' as _i16;
import 'package:flutter/foundation.dart' as _i34;
import 'package:flutter_bloc/flutter_bloc.dart' as _i26;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i14;
import 'package:frontend/blocs/user/register_bloc.dart' as _i24;
import 'package:frontend/events/user/register_events.dart' as _i25;
import 'package:frontend/foodini.dart' as _i38;
import 'package:frontend/models/diet_generation/custom_meal_update_request.dart'
    as _i37;
import 'package:frontend/models/diet_generation/daily_meals_create.dart'
    as _i35;
import 'package:frontend/models/diet_generation/meal_create.dart' as _i12;
import 'package:frontend/models/diet_generation/meal_icon_info.dart' as _i13;
import 'package:frontend/models/diet_generation/meal_info_update_request.dart'
    as _i36;
import 'package:frontend/models/diet_generation/meal_recipe.dart' as _i11;
import 'package:frontend/models/diet_generation/meal_type.dart' as _i33;
import 'package:frontend/models/user/change_language_request.dart' as _i23;
import 'package:frontend/models/user/change_password_request.dart' as _i22;
import 'package:frontend/models/user/default_response.dart' as _i5;
import 'package:frontend/models/user/language.dart' as _i31;
import 'package:frontend/models/user/logged_user.dart' as _i4;
import 'package:frontend/models/user/login_request.dart' as _i19;
import 'package:frontend/models/user/provide_email_request.dart' as _i21;
import 'package:frontend/models/user/refreshed_tokens_response.dart' as _i6;
import 'package:frontend/models/user/register_request.dart' as _i20;
import 'package:frontend/models/user/user_response.dart' as _i3;
import 'package:frontend/models/user_details/diet_form.dart' as _i9;
import 'package:frontend/models/user_details/macros.dart' as _i29;
import 'package:frontend/models/user_details/predicted_calories.dart' as _i10;
import 'package:frontend/repository/api_client.dart' as _i2;
import 'package:frontend/repository/diet_generation/diet_prediction_repository.dart'
    as _i30;
import 'package:frontend/repository/diet_generation/meals_repository.dart'
    as _i32;
import 'package:frontend/repository/user/user_repository.dart' as _i7;
import 'package:frontend/repository/user_details/user_details_repository.dart'
    as _i28;
import 'package:frontend/services/token_storage_service.dart' as _i27;
import 'package:frontend/states/register_states.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_1 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoggedUser_2 extends _i1.SmartFake implements _i4.LoggedUser {
  _FakeLoggedUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDefaultResponse_3 extends _i1.SmartFake
    implements _i5.DefaultResponse {
  _FakeDefaultResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshedTokensResponse_4 extends _i1.SmartFake
    implements _i6.RefreshedTokensResponse {
  _FakeRefreshedTokensResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserRepository_5 extends _i1.SmartFake
    implements _i7.UserRepository {
  _FakeUserRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterState_6 extends _i1.SmartFake implements _i8.RegisterState {
  _FakeRegisterState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDietForm_7 extends _i1.SmartFake implements _i9.DietForm {
  _FakeDietForm_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePredictedCalories_8 extends _i1.SmartFake
    implements _i10.PredictedCalories {
  _FakePredictedCalories_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealRecipe_9 extends _i1.SmartFake implements _i11.MealRecipe {
  _FakeMealRecipe_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealCreate_10 extends _i1.SmartFake implements _i12.MealCreate {
  _FakeMealCreate_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealIconInfo_11 extends _i1.SmartFake implements _i13.MealIconInfo {
  _FakeMealIconInfo_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_12 extends _i1.SmartFake implements _i14.IOSOptions {
  _FakeIOSOptions_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_13 extends _i1.SmartFake
    implements _i14.AndroidOptions {
  _FakeAndroidOptions_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_14 extends _i1.SmartFake implements _i14.LinuxOptions {
  _FakeLinuxOptions_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_15 extends _i1.SmartFake
    implements _i14.WindowsOptions {
  _FakeWindowsOptions_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_16 extends _i1.SmartFake implements _i14.WebOptions {
  _FakeWebOptions_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_17 extends _i1.SmartFake implements _i14.MacOsOptions {
  _FakeMacOsOptions_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_18<T> extends _i1.SmartFake implements _i15.Response<T> {
  _FakeResponse_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptorState_19<T> extends _i1.SmartFake
    implements _i16.InterceptorState<T> {
  _FakeInterceptorState_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_20 extends _i1.SmartFake implements _i17.Locale {
  _FakeLocale_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_21 extends _i1.SmartFake implements _i15.BaseOptions {
  _FakeBaseOptions_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_22 extends _i1.SmartFake
    implements _i15.HttpClientAdapter {
  _FakeHttpClientAdapter_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_23 extends _i1.SmartFake implements _i15.Transformer {
  _FakeTransformer_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_24 extends _i1.SmartFake implements _i15.Interceptors {
  _FakeInterceptors_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_25 extends _i1.SmartFake implements _i15.Dio {
  _FakeDio_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i18.Future<_i3.UserResponse> getUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i18.Future<_i3.UserResponse>.value(
              _FakeUserResponse_1(this, Invocation.method(#getUser, [userId])),
            ),
          )
          as _i18.Future<_i3.UserResponse>);

  @override
  _i18.Future<_i4.LoggedUser> login(_i19.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i18.Future<_i4.LoggedUser>.value(
              _FakeLoggedUser_2(this, Invocation.method(#login, [request])),
            ),
          )
          as _i18.Future<_i4.LoggedUser>);

  @override
  _i18.Future<void> logout(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> resendVerificationMail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationMail, [email]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> delete(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [userId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i5.DefaultResponse?> register(_i20.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i18.Future<_i5.DefaultResponse?>.value(),
          )
          as _i18.Future<_i5.DefaultResponse?>);

  @override
  _i18.Future<_i5.DefaultResponse> provideEmail(
    _i21.ProvideEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#provideEmail, [request]),
            returnValue: _i18.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#provideEmail, [request]),
              ),
            ),
          )
          as _i18.Future<_i5.DefaultResponse>);

  @override
  _i18.Future<_i5.DefaultResponse> changePassword(
    _i22.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i18.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i18.Future<_i5.DefaultResponse>);

  @override
  _i18.Future<_i5.DefaultResponse> changeLanguage(
    _i23.ChangeLanguageRequest? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [request, userId]),
            returnValue: _i18.Future<_i5.DefaultResponse>.value(
              _FakeDefaultResponse_3(
                this,
                Invocation.method(#changeLanguage, [request, userId]),
              ),
            ),
          )
          as _i18.Future<_i5.DefaultResponse>);

  @override
  _i18.Future<_i6.RefreshedTokensResponse> refreshTokens(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [userId]),
            returnValue: _i18.Future<_i6.RefreshedTokensResponse>.value(
              _FakeRefreshedTokensResponse_4(
                this,
                Invocation.method(#refreshTokens, [userId]),
              ),
            ),
          )
          as _i18.Future<_i6.RefreshedTokensResponse>);
}

/// A class which mocks [RegisterBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterBloc extends _i1.Mock implements _i24.RegisterBloc {
  MockRegisterBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.UserRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeUserRepository_5(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i7.UserRepository);

  @override
  _i8.RegisterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeRegisterState_6(this, Invocation.getter(#state)),
          )
          as _i8.RegisterState);

  @override
  _i18.Stream<_i8.RegisterState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i8.RegisterState>.empty(),
          )
          as _i18.Stream<_i8.RegisterState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i25.RegisterEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i25.RegisterEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i8.RegisterState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i25.RegisterEvent?>(
    _i26.EventHandler<E, _i8.RegisterState>? handler, {
    _i26.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i26.Transition<_i25.RegisterEvent?, _i8.RegisterState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void onChange(_i26.Change<_i8.RegisterState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TokenStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageService extends _i1.Mock
    implements _i27.TokenStorageService {
  MockTokenStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);

  @override
  _i18.Future<void> deleteAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);

  @override
  _i18.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [UserDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailsRepository extends _i1.Mock
    implements _i28.UserDetailsRepository {
  MockUserDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i18.Future<_i9.DietForm> getDietPreferences(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDietPreferences, [userId]),
            returnValue: _i18.Future<_i9.DietForm>.value(
              _FakeDietForm_7(
                this,
                Invocation.method(#getDietPreferences, [userId]),
              ),
            ),
          )
          as _i18.Future<_i9.DietForm>);

  @override
  _i18.Future<void> submitDietForm(_i9.DietForm? request, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#submitDietForm, [request, userId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i10.PredictedCalories> submitMacrosChange(
    _i29.Macros? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitMacrosChange, [request, userId]),
            returnValue: _i18.Future<_i10.PredictedCalories>.value(
              _FakePredictedCalories_8(
                this,
                Invocation.method(#submitMacrosChange, [request, userId]),
              ),
            ),
          )
          as _i18.Future<_i10.PredictedCalories>);

  @override
  _i18.Future<_i10.PredictedCalories> addCaloriesPrediction(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addCaloriesPrediction, [userId]),
            returnValue: _i18.Future<_i10.PredictedCalories>.value(
              _FakePredictedCalories_8(
                this,
                Invocation.method(#addCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i18.Future<_i10.PredictedCalories>);

  @override
  _i18.Future<_i10.PredictedCalories> getCaloriesPrediction(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCaloriesPrediction, [userId]),
            returnValue: _i18.Future<_i10.PredictedCalories>.value(
              _FakePredictedCalories_8(
                this,
                Invocation.method(#getCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i18.Future<_i10.PredictedCalories>);
}

/// A class which mocks [DietPredictionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDietPredictionRepository extends _i1.Mock
    implements _i30.DietPredictionRepository {
  MockDietPredictionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i18.Future<_i11.MealRecipe> getMealRecipe(
    int? userId,
    int? mealRecipeId,
    _i31.Language? language,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealRecipe, [userId, mealRecipeId, language]),
            returnValue: _i18.Future<_i11.MealRecipe>.value(
              _FakeMealRecipe_9(
                this,
                Invocation.method(#getMealRecipe, [
                  userId,
                  mealRecipeId,
                  language,
                ]),
              ),
            ),
          )
          as _i18.Future<_i11.MealRecipe>);

  @override
  _i18.Future<void> generateMealPlan(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#generateMealPlan, [userId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [MealsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealsRepository extends _i1.Mock implements _i32.MealsRepository {
  MockMealsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i18.Future<_i12.MealCreate> getMealDetails(int? mealId, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMealDetails, [mealId, userId]),
            returnValue: _i18.Future<_i12.MealCreate>.value(
              _FakeMealCreate_10(
                this,
                Invocation.method(#getMealDetails, [mealId, userId]),
              ),
            ),
          )
          as _i18.Future<_i12.MealCreate>);

  @override
  _i18.Future<_i13.MealIconInfo> getMealIconInfo(
    int? userId,
    _i33.MealType? mealType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealIconInfo, [userId, mealType]),
            returnValue: _i18.Future<_i13.MealIconInfo>.value(
              _FakeMealIconInfo_11(
                this,
                Invocation.method(#getMealIconInfo, [userId, mealType]),
              ),
            ),
          )
          as _i18.Future<_i13.MealIconInfo>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i14.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_12(this, Invocation.getter(#iOptions)),
          )
          as _i14.IOSOptions);

  @override
  _i14.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_13(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i14.AndroidOptions);

  @override
  _i14.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_14(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i14.LinuxOptions);

  @override
  _i14.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_15(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i14.WindowsOptions);

  @override
  _i14.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_16(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i14.WebOptions);

  @override
  _i14.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_17(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i14.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i34.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i34.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> write({
    required String? key,
    required String? value,
    _i14.IOSOptions? iOptions,
    _i14.AndroidOptions? aOptions,
    _i14.LinuxOptions? lOptions,
    _i14.WebOptions? webOptions,
    _i14.MacOsOptions? mOptions,
    _i14.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<String?> read({
    required String? key,
    _i14.IOSOptions? iOptions,
    _i14.AndroidOptions? aOptions,
    _i14.LinuxOptions? lOptions,
    _i14.WebOptions? webOptions,
    _i14.MacOsOptions? mOptions,
    _i14.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);

  @override
  _i18.Future<bool> containsKey({
    required String? key,
    _i14.IOSOptions? iOptions,
    _i14.AndroidOptions? aOptions,
    _i14.LinuxOptions? lOptions,
    _i14.WebOptions? webOptions,
    _i14.MacOsOptions? mOptions,
    _i14.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i18.Future<bool>.value(false),
          )
          as _i18.Future<bool>);

  @override
  _i18.Future<void> delete({
    required String? key,
    _i14.IOSOptions? iOptions,
    _i14.AndroidOptions? aOptions,
    _i14.LinuxOptions? lOptions,
    _i14.WebOptions? webOptions,
    _i14.MacOsOptions? mOptions,
    _i14.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<Map<String, String>> readAll({
    _i14.IOSOptions? iOptions,
    _i14.AndroidOptions? aOptions,
    _i14.LinuxOptions? lOptions,
    _i14.WebOptions? webOptions,
    _i14.MacOsOptions? mOptions,
    _i14.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i18.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i18.Future<Map<String, String>>);

  @override
  _i18.Future<void> deleteAll({
    _i14.IOSOptions? iOptions,
    _i14.AndroidOptions? aOptions,
    _i14.LinuxOptions? lOptions,
    _i14.WebOptions? webOptions,
    _i14.MacOsOptions? mOptions,
    _i14.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i18.Future<bool?>.value(),
          )
          as _i18.Future<bool?>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i15.Response<dynamic>> getUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getUser, [userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> register(_i20.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> login(_i19.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> provideEmail(
    _i21.ProvideEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#provideEmail, [request]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#provideEmail, [request]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> changePassword(
    _i22.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> changeLanguage(
    _i23.ChangeLanguageRequest? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [request, userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#changeLanguage, [request, userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> refreshTokens(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, [userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#refreshTokens, [userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> logout(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#logout, [userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> resendVerificationMail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationMail, [email]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#resendVerificationMail, [email]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> delete(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#delete, [userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> refreshRequest(
    _i15.RequestOptions? requestOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshRequest, [requestOptions]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#refreshRequest, [requestOptions]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> getDietPreferences(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDietPreferences, [userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getDietPreferences, [userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> submitDietForm(
    _i9.DietForm? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitDietForm, [request, userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#submitDietForm, [request, userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> submitMacrosChange(
    _i29.Macros? request,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitMacrosChange, [request, userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#submitMacrosChange, [request, userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> addCaloriesPrediction(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addCaloriesPrediction, [userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#addCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> getCaloriesPrediction(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCaloriesPrediction, [userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getCaloriesPrediction, [userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> getMealRecipe(
    int? recipeId,
    _i31.Language? language,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealRecipe, [recipeId, language, userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getMealRecipe, [recipeId, language, userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> generateMealPlan(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#generateMealPlan, [userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#generateMealPlan, [userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> getDailySummaryMeals(
    DateTime? day,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummaryMeals, [day, userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getDailySummaryMeals, [day, userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> addDailySummaryMeals(
    _i35.DailyMealsCreate? dailyMealsCreate,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDailySummaryMeals, [
              dailyMealsCreate,
              userId,
            ]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#addDailySummaryMeals, [
                  dailyMealsCreate,
                  userId,
                ]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> updateDailySummaryMeals(
    _i36.MealInfoUpdateRequest? mealInfoUpdateRequest,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDailySummaryMeals, [
              mealInfoUpdateRequest,
              userId,
            ]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#updateDailySummaryMeals, [
                  mealInfoUpdateRequest,
                  userId,
                ]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> addCustomMeal(
    _i37.CustomMealUpdateRequest? customMealUpdateRequest,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCustomMeal, [
              customMealUpdateRequest,
              userId,
            ]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#addCustomMeal, [
                  customMealUpdateRequest,
                  userId,
                ]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> getDailySummaryMacros(
    DateTime? day,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummaryMacros, [day, userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getDailySummaryMacros, [day, userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> addDailySummaryMacros(
    _i35.DailyMealsCreate? dailyMealsCreate,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDailySummaryMacros, [
              dailyMealsCreate,
              userId,
            ]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#addDailySummaryMacros, [
                  dailyMealsCreate,
                  userId,
                ]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> getMealDetails(
    int? mealId,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealDetails, [mealId, userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getMealDetails, [mealId, userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> getMealIconInfo(
    _i33.MealType? mealType,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMealIconInfo, [mealType, userId]),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(#getMealIconInfo, [mealType, userId]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);
}

/// A class which mocks [ErrorInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorInterceptorHandler extends _i1.Mock
    implements _i15.ErrorInterceptorHandler {
  MockErrorInterceptorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i16.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i18.Future<_i16.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_19<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
          )
          as _i18.Future<_i16.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(Invocation.getter(#isCompleted), returnValue: false)
          as bool);

  @override
  void next(_i15.DioException? error) => super.noSuchMethod(
    Invocation.method(#next, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(_i15.Response<dynamic>? response) => super.noSuchMethod(
    Invocation.method(#resolve, [response]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(_i15.DioException? error) => super.noSuchMethod(
    Invocation.method(#reject, [error]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LanguageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageCubit extends _i1.Mock implements _i38.LanguageCubit {
  MockLanguageCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Locale get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeLocale_20(this, Invocation.getter(#state)),
          )
          as _i17.Locale);

  @override
  _i18.Stream<_i17.Locale> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i17.Locale>.empty(),
          )
          as _i18.Stream<_i17.Locale>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i18.Future<void> change(_i31.Language? language) =>
      (super.noSuchMethod(
            Invocation.method(#change, [language]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void emit(_i17.Locale? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i26.Change<_i17.Locale>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i15.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_21(this, Invocation.getter(#options)),
          )
          as _i15.BaseOptions);

  @override
  _i15.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_22(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i15.HttpClientAdapter);

  @override
  _i15.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_23(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i15.Transformer);

  @override
  _i15.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_24(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i15.Interceptors);

  @override
  set options(_i15.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i15.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i15.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<_i15.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
    _i15.ProgressCallback? onSendProgress,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
    _i15.ProgressCallback? onSendProgress,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
    _i15.ProgressCallback? onSendProgress,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
    _i15.ProgressCallback? onSendProgress,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
    _i15.ProgressCallback? onSendProgress,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
    _i15.ProgressCallback? onSendProgress,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i15.Options? options,
    _i15.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i15.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i15.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i15.FileAccessMode? fileAccessMode = _i15.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i15.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i15.ProgressCallback? onReceiveProgress,
    _i15.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i15.FileAccessMode? fileAccessMode = _i15.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i15.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i18.Future<_i15.Response<dynamic>>.value(
              _FakeResponse_18<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<dynamic>>);

  @override
  _i18.Future<_i15.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i15.CancelToken? cancelToken,
    _i15.Options? options,
    _i15.ProgressCallback? onSendProgress,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i15.CancelToken? cancelToken,
    _i15.Options? options,
    _i15.ProgressCallback? onSendProgress,
    _i15.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i18.Future<_i15.Response<T>> fetch<T>(_i15.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i18.Future<_i15.Response<T>>.value(
              _FakeResponse_18<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i18.Future<_i15.Response<T>>);

  @override
  _i15.Dio clone({
    _i15.BaseOptions? options,
    _i15.Interceptors? interceptors,
    _i15.HttpClientAdapter? httpClientAdapter,
    _i15.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_25(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i15.Dio);
}
